
import { Quote, UserHabits } from './types';

export const INITIAL_HABITS: UserHabits = {
  name: '',
  age: 25,
  gender: 'male',
  height: 170,
  weight: 70,
  smoking: 'none',
  drinking: 'none',
  sleep: 7,
  water: 8,
  stress: 'moderate',
  depression: 'stable',
  screenTime: 4,
  exercise: 30,
  yoga: false,
  junkFood: 'often',
  sugar: 'little',
  processedMeat: 'sometimes',
  cityLiving: false,
  socialLife: 'good',
  medicalCheckup: 'annually',
  medicalConditions: [],
};

export const MEDICAL_CONDITION_LIST = [
  { id: 'hypertension', label: 'High Blood Pressure' },
  { id: 'diabetes', label: 'Diabetes (Type 1/2)' },
  { id: 'heart_disease', label: 'Heart Issues' },
  { id: 'asthma', label: 'Asthma / Breathing' },
  { id: 'cholesterol', label: 'High Cholesterol' },
  { id: 'kidney', label: 'Kidney Disease' },
  { id: 'cancer', label: 'Cancer (Current/History)' },
  { id: 'autoimmune', label: 'Autoimmune Disease' },
  { id: 'thyroid', label: 'Thyroid Issues' },
];

export const LIFE_QUOTES: Quote[] = [
  { text: "The boundaries between life and death are at best shadowy and vague.", author: "Edgar Allan Poe" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Every man must do two things alone; he must do his own believing and his own dying.", author: "Martin Luther" },
  { text: "To the well-organized mind, death is but the next great adventure.", author: "Albus Dumbledore" },
  { text: "Life is a hard cycle of suffering.", author: "Unknown" },
  { text: "Do not fear death so much but rather the inadequate life.", author: "Bertolt Brecht" },
  { text: "The fear of death follows from the fear of life.", author: "Mark Twain" },
  { text: "Live as if you were to die tomorrow.", author: "Mahatma Gandhi" },
  { text: "While I thought that I was learning how to live, I have been learning how to die.", author: "Leonardo da Vinci" },
  { text: "Life is pleasant. Death is peaceful. It's the transition that's troublesome.", author: "Isaac Asimov" },
  { text: "No one escapes the final tap on the shoulder.", author: "The Devil" },
  { text: "Dust you are, and to dust you shall return.", author: "Genesis" },
  { text: "Life is but a walking shadow.", author: "William Shakespeare" },
  { text: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
  { text: "Our death is not an end if we can live on in our children and the younger generation.", author: "Albert Einstein" },
  { text: "Death is the destination we all share. No one has ever escaped it.", author: "Steve Jobs" },
  { text: "The goal of all life is death.", author: "Sigmund Freud" },
  { text: "We all die. The goal isn't to live forever, the goal is to create something that will.", author: "Chuck Palahniuk" },
  { text: "Death is beautiful when seen as a law, and not as an accident.", author: "Henry David Thoreau" },
  { text: "The cradle rocks above an abyss.", author: "Vladimir Nabokov" },
  { text: "The clock is ticking. Can you hear it?", author: "The Keeper" },
  { text: "Hell is empty and all the devils are here.", author: "William Shakespeare" },
  { text: "Life is a series of natural and spontaneous changes.", author: "Lao Tzu" },
  { text: "Only the dead have seen the end of war.", author: "Plato" },
  { text: "Cowards die many times before their deaths.", author: "William Shakespeare" },
  { text: "Death is not the greatest loss in life. The greatest loss is what dies inside us while we live.", author: "Norman Cousins" },
  { text: "Better to reign in Hell than serve in Heaven.", author: "John Milton" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "He who is not busy being born is busy dying.", author: "Bob Dylan" },
  { text: "Everything that has a beginning has an end.", author: "The Oracle" }
];
